Project2_NewDB/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project2_NewDB.Models;

namespace Project2_NewDB.Controllers
{
    public class HoaDonsController : Controller
    {
        private readonly QuanLyBanHangContext _context;

        public HoaDonsController(QuanLyBanHangContext context)
        {
            _context = context;
        }

        // GET: HoaDons
        public async Task<IActionResult> Index()
        {
            var quanLyBanHangContext = _context.HoaDons.Include(h => h.MaKhNavigation);
            return View(await quanLyBanHangContext.ToListAsync());
        }

        // GET: HoaDons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }

        // GET: HoaDons/Create
        public IActionResult Create()
        {
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh");
            return View();
        }

        // POST: HoaDons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHd,NgayLap,TongTien,MaKh,TrangThai")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoaDon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            return View(hoaDon);
        }

        // GET: HoaDons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon == null)
            {
                return NotFound();
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            return View(hoaDon);
        }

        // POST: HoaDons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHd,NgayLap,TongTien,MaKh,TrangThai")] HoaDon hoaDon)
        {
            if (id != hoaDon.MaHd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoaDon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoaDonExists(hoaDon.MaHd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            return View(hoaDon);
        }

        // GET: HoaDons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }

        // POST: HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon != null)
            {
                _context.HoaDons.Remove(hoaDon);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoaDonExists(int id)
        {
            return _context.HoaDons.Any(e => e.MaHd == id);
        }
    }
}

Project2_NewDB/Controllers/SanPhamsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using Project2_NewDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project2_NewDB.Controllers
{
    public class SanPhamsController : Controller
    {
        private readonly QuanLyBanHangContext _context;

        public SanPhamsController(QuanLyBanHangContext context)
        {
            _context = context;
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            var quanLyBanHangContext = _context.SanPhams.Include(s => s.MaLoaiNavigation);
            return View(await quanLyBanHangContext.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            ViewData["MaLoai"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSp,TenSp,MoTa,DonGia,SoLuong,MaLoai,HinhAnhFile")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                if (sanPham.HinhAnhFile != null && sanPham.HinhAnhFile.Length > 0)
                {
                    // Tạo folder lưu ảnh: wwwroot/images/product
                    var uploads = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/product");
                    if (!Directory.Exists(uploads))
                    {
                        Directory.CreateDirectory(uploads);
                    }

                    // Tạo tên file duy nhất
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(sanPham.HinhAnhFile.FileName);
                    var filePath = Path.Combine(uploads, fileName);

                    // Lưu file
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await sanPham.HinhAnhFile.CopyToAsync(fileStream);
                    }

                    // Lưu URL vào MoTa
                    sanPham.MoTa = $"/images/product/{fileName}";
                }

                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "MaLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }

            ViewData["MaLoai"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSp,TenSp,MoTa,DonGia,SoLuong,MaLoai,HinhAnhFile")] SanPham sanPham)
        {
            if (id != sanPham.MaSp)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingProduct = await _context.SanPhams.FindAsync(id);

                    if (existingProduct == null)
                        return NotFound();

                    // Xử lý upload ảnh mới
                    if (sanPham.HinhAnhFile != null && sanPham.HinhAnhFile.Length > 0)
                    {
                        // Xóa ảnh cũ nếu có
                        if (!string.IsNullOrEmpty(existingProduct.MoTa))
                        {
                            var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", existingProduct.MoTa.TrimStart('/').Replace('/', Path.DirectorySeparatorChar));
                            if (System.IO.File.Exists(oldFilePath))
                            {
                                System.IO.File.Delete(oldFilePath);
                            }
                        }

                        // Lưu ảnh mới
                        var uploads = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/product");
                        if (!Directory.Exists(uploads))
                            Directory.CreateDirectory(uploads);

                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(sanPham.HinhAnhFile.FileName);
                        var filePath = Path.Combine(uploads, fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await sanPham.HinhAnhFile.CopyToAsync(fileStream);
                        }

                        existingProduct.MoTa = $"/images/product/{fileName}";
                    }

                    // Cập nhật các thông tin còn lại
                    existingProduct.TenSp = sanPham.TenSp;
                    existingProduct.DonGia = sanPham.DonGia;
                    existingProduct.SoLuong = sanPham.SoLuong;
                    existingProduct.MaLoai = sanPham.MaLoai;

                    _context.Update(existingProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSp))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["MaLoai"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // Private helper method
        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }
        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);

            if (sanPham == null)
                return NotFound();

            return View(sanPham);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
                return NotFound();

            // Lưu đường dẫn file ảnh để xóa sau nếu database xóa thành công
            string filePath = null;
            if (!string.IsNullOrEmpty(sanPham.MoTa))
            {
                var relativePath = sanPham.MoTa.TrimStart('/');
                filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", relativePath.Replace('/', Path.DirectorySeparatorChar));
            }

            try
            {
                // Thử xóa sản phẩm khỏi database
                _context.SanPhams.Remove(sanPham);
                await _context.SaveChangesAsync();

                // Nếu database xóa thành công, xóa file ảnh
                if (filePath != null && System.IO.File.Exists(filePath))
                {
                    try
                    {
                        System.IO.File.Delete(filePath);
                    }
                    catch
                    {
                        // Bỏ qua lỗi xóa file ảnh
                    }
                }
            }
            catch (DbUpdateException)
            {
                // Lỗi khóa ngoại
                TempData["Error"] = "Cannot delete product because it is referenced by other records. Please remove related data first.";
                return RedirectToAction(nameof(Delete), new { id });
            }
            catch (Exception ex)
            {
                // Các lỗi khác
                TempData["Error"] = "Cannot delete product: " + ex.Message;
                return RedirectToAction(nameof(Delete), new { id });
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Project2_NewDB/Views/Shared/_Carousel.cshtml
<div id="mainCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://tungkysie05.id.vn/Carousel1.png" class="d-block mx-auto" style="width: 80%; height: 250px; object-fit: cover;" alt="Image 1">
        </div>
        <div class="carousel-item">
            <img src="https://tungkysie05.id.vn/Carousel1.png" class="d-block mx-auto" style="width: 80%; height: 250px; object-fit: cover;" alt="Image 2">
        </div>
        <div class="carousel-item">
            <img src="https://tungkysie05.id.vn/Carousel1.png" class="d-block mx-auto" style="width: 80%; height: 250px; object-fit: cover;" alt="Image 3">
        </div>
    </div>
</div>

Project2_NewDB/Views/Shared/_Footer.cshtml
    <div class="container">
        <div class="row">
            <!-- About Section -->
            <div class="col-md-4 mb-4">
                <h5 class="text-primary mb-3">Về Chúng Tôi</h5>
                <p class="text-secondary">
                    Hệ thống quản lý hàng hóa chuyên nghiệp, giúp bạn quản lý kho hàng hiệu quả và dễ dàng.
                </p>
            </div>
            <!-- Contact Section -->
            <div class="col-md-4 mb-4">
                <h5 class="text-primary mb-3">Liên Hệ</h5>
                <ul class="list-unstyled">
                    <li class="mb-2"><i class="fas fa-map-marker-alt me-2"></i>157 Phố Xốm, Hà Đông, Hà Nội</li>
                    <li class="mb-2"><i class="fas fa-phone me-2"></i>0334402527</li>
                    <li><i class="fas fa-envelope me-2"></i>kobayashi.siesta@gmail.com</li>
                </ul>
            </div>
            <!-- Quick Links Section -->
            <div class="col-md-4 mb-4">
                <h5 class="text-primary mb-3">Liên Kết Nhanh</h5>
                <ul class="list-unstyled">
                    <li class="mb-2"><a href="/" class="text-secondary text-decoration-none"><i class="fas fa-home me-2"></i>Trang chủ</a></li>
                    <li class="mb-2"><a href="#" class="text-secondary text-decoration-none"><i class="fas fa-question-circle me-2"></i>Hướng dẫn</a></li>
                    <li><a href="#" class="text-secondary text-decoration-none"><i class="fas fa-user-shield me-2"></i>Chính sách bảo mật</a></li>
                </ul>
            </div>
        </div>
        <hr class="bg-secondary">
        <div class="row align-items-center">
            <div class="col-md-6 text-center text-md-start pb-3 mb-3 mb-md-0">
                <small class="text-secondary ">
                    &copy; @DateTime.Now.Year Hệ Thống Quản Lý Hàng Hóa. Bảo lưu mọi quyền.
                </small>
            </div>
        </div>
    </div>

Project2_NewDB/Views/Shared/_Header.cshtml
@* Bootstrap-optimized header *@
<header class="navbar navbar-light bg-light border-bottom px-3 py-2">
    <!-- Logo linking to Facebook -->
    <a class="navbar-brand d-flex align-items-center" href="https://facebook.com/" target="_blank">
        <img src="https://tungkysie05.id.vn/image/app_icon.png" alt="Logo" style="height: 32px; width: 32px; object-fit: contain;" />
    </a>
    <!-- Centered shop name -->
    <a href="" class="mx-auto fw-bold fs-5 text-center text-decoration-none">
        Tạp Hóa NemeChua
    </a>
    <!-- Login text -->
    <div>
        <a href="#" class="text-primary text-decoration-none">Đăng nhập</a>
    </div>
</header>

Project2_NewDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="https://tungkysie05.id.vn/image/app_icon.png" type="image/png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
    <header>
        @Html.Partial("_Header")
    </header>
    <carousel>
        @Html.Partial("_Carousel")
    </carousel>
    <nav>
        @Html.Partial("_Navbar")
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark text-light pt-5 mt-5">
        @Html.Partial("_Footer")
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project2_NewDB/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="https://tungkysie05.id.vn/image/app_icon.png" type="image/png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
    <header>
        @Html.Partial("_Header")
    </header>
    <nav>
        @Html.Partial("_NavbarAdmin")
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project2_NewDB/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Project2_NewDB/Views/Shared/_NavbarAdmin.cshtml
<div class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="LoaiSanPhams" asp-action="Index">Loại Sản Phẩm</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="SanPhams" asp-action="Index">Sản Phẩm</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="KhachHangs" asp-action="Index">Khách</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="QuanTriViens" asp-action="Index">Quản Trị Viên</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="HoaDons" asp-action="Index">Hoa Don</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="ChiTietHoaDons" asp-action="Index">Chi Tiet Hoa Don</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">TestLayout</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Project2_NewDB/Views/Shared/_SearchBar.cshtml
<div class="search-container">
    <div class="search-bar">
        <!-- Logo bên trái -->
        <div class="logo">
            <img src="https://tungkysie05.id.vn/logo.png" alt="Logo">
        </div>

        <!-- Thanh tìm kiếm ở giữa -->
        <div class="search-form">
            <input class="search-input" type="search" placeholder="Tìm kiếm sản phẩm...">
            <button class="search-btn" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </div>

        <!-- Giỏ hàng bên phải -->
        <a href="#" class="cart-icon">
            <i class="fas fa-shopping-cart"></i>
            <span class="cart-count">3</span>
        </a>
    </div>
</div>